### ISSUE TITLE
{"error":"invalid_client"}

### ISSUE THREAD

**Issue by Tlacatecolototl** [bmsimons/ps-spotify#6]
The latest version of ps-spotify (Wooo official update!) seems to spit "{"error":"invalid_client"}" with every cmdlet, but still returns the output properly.

I presume this is because I specified an access token and refresh token in the psm1, but did not provide SpotifyBasicBearer. I put in the info that the spec requests (https://developer.spotify.com/web-api/authorization-guide/ "Base 64 encoded string that contains the client ID and client secret key. The field must have the format: Authorization: Basic <base64 encoded client_id:client_secret>") and it works fine.

I'm not sure if i'm reading the readme incorrectly, or if it's just late, but I think it could use a little bit of clarification.

Thanks a ton for the latest update though! I just happened to be revisiting some of my older Spotify scripts and noticed it was updated. I also may just be missing or mis-reading something blatantly obvious, please let me know if this is the case! I've been up for too long 😄

**Comment by bmsimons** [comment]
Thanks for reaching out!

I was rushing things and it turned out that I made a mistake in the instructions given in the readme file (which have been fixed by commit 92dc1f8). Indeed, the SpotifyBasicBearer string needs to have the base64 encoded string of client_id:client_secret

Feel free to check out the article on my website that I have written. It contains some examples that might be inspirational in some way. Links to this can also be found inside the readme file.

Thanks for reporting and have a nice day :)
